server:
  port: 8769
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@127.0.0.1:8761/eureka
  instance:
    prefer-ip-address: true # 但其他服务获取地址时提供ip而不是hostname
    ip-address: 127.0.0.1 # 指定自己的ip信息,不指定的话会自己寻找
# 暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  # 数据源
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/eshop?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    # Jasypt加密 可到common-utils中找到JasyptUtil加解密工具类生成加密结果 格式为ENC(加密结果)
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    # Druid StatViewServlet配置
    druid:
      stat-view-servlet:
        # 默认true 内置监控页面首页/druid/index.html
        enabled: true
        url-pattern: /druid/*
        # 允许清空统计数据
        reset-enable: true
        login-username: root
        login-password: root
        # IP白名单 多个逗号分隔
        allow:
        # IP黑名单
        deny:
  jpa:
    show-sql: true
    #自动生成表结构
    generate-ddl: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  application:
    name: product-server
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    #支持发布确认
    publisher-confirms: true
    #支持发布返回
    publisher-returns: true
    listener:
      simple:
        #采用手动应答
        acknowledge-mode: manual
        #指定最大消费数量
        max-concurrency: 1
        #指定最小的消费数量
        concurrency: 1
        retry:
          #是否开启重试机制
          enabled: true
        prefetch: 10
    connection-timeout: 50000
    template:
      retry:
        enabled: true
      receive-timeout: 10000

# Mybatis-plus
mybatis-plus:
  # 放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath:/mapper/*Mapper.xml
  # 实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.springcloud.eshop.product.server.entity
  typeEnumsPackage: com.springcloud.eshop.product.server.entity
  global-config:
    # 主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 2
    # 字段策略 0:"忽略判断",1:"非 NULL 判断",2:"非空判断"
    field-strategy: 2
    # 驼峰下划线转换
    db-column-underline: true
    # 刷新mapper 调试神器
    refresh-mapper: true
    # 数据库大写下划线转换
    # capital-mode: true
    # 逻辑删除配置（下面3个配置）
    logic-delete-value: 0
    logic-not-delete-value: 1
    # SQL 解析缓存，开启后多租户 @SqlParser 注解生效
    sql-parser-cache: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

# Swagger界面内容配置
swagger:
  title: XBoot API接口文档
  description: XBoot Api Documentation
  version: 1.0.0
  termsOfServiceUrl: http://blog.exrick.cn
  contact:
    name: Exrick
    url: http://blog.exrick.cn
    email: 1012139570@qq.com
